version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: 21778821
      POSTGRES_DB: library
#  adminer:
#    image: adminer:4.7.8-standalone
#    restart: always
#    ports:
#      - 8090:8090
#    depends_on:
#      - db
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py migrate
      && python3 manage.py create_data
      && python3 manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db