version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    expose:
      - 5432
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: 21778821
      POSTGRES_DB: todoservice

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8090:8080
    depends_on:
      
      - db

  backend:
    build:
      context: .
    ports:
      - 8010:8050
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py collectstatic --noinput
      && gunicorn todoservice.wsgi -b 0.0.0.0:8050
      "
    volumes:
      - /static:/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - /static:/static
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 90:80
    depends_on:
      - nginx

#      && python3 manage.py makemigrations usersapp
#      && python3 manage.py makemigrations todoapp
#      && python3 manage.py migrate
#      && python3 manage.py create_superuser
#      && python3 manage.py create_users 20
#      && python3 manage.py create_projects 20 40