version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aleksandr
      POSTGRES_PASSWORD: 21778821
      POSTGRES_DB: todoservice

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db
  backend:
    build:
      context: .
    expose:
      - 8050
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py migrate
      && gunicorn todoservice.wsgi -b 0.0.0.0:8050
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend