# Generated by Django 3.2.7 on 2021-09-10 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='todo',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
