# Generated by Django 3.2.7 on 2021-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210912_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='uuid',
        ),
    ]
