# Generated by Django 3.2.7 on 2021-09-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210910_1056'),
        ('todoapp', '0004_auto_20210912_1220'),
    ]

    operations = [
    ]
