# Generated by Django 3.2.7 on 2021-09-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20210916_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='id',
            new_name='uuid',
        ),
    ]
